
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CONDITION DEVICE IF OFF ON TURNrule : TURN action DEVICE IF CONDITIONaction : ON\n              | OFF'
    
_lr_action_items = {'TURN':([0,],[2,]),'$end':([1,8,],[0,-1,]),'ON':([2,],[4,]),'OFF':([2,],[5,]),'DEVICE':([3,4,5,],[6,-2,-3,]),'IF':([6,],[7,]),'CONDITION':([7,],[8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'rule':([0,],[1,]),'action':([2,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> rule","S'",1,None,None,None),
  ('rule -> TURN action DEVICE IF CONDITION','rule',5,'p_rule','parser.py',24),
  ('action -> ON','action',1,'p_action','parser.py',28),
  ('action -> OFF','action',1,'p_action','parser.py',29),
]
